specfile_path: dist/beakerlib.spec

files_to_sync:
  - src: dist/*
    dest: .
  - .packit.yaml

upstream_package_name: beakerlib
downstream_package_name: beakerlib

actions:
    changelog-entry:
      - "bash -c 'rpm -q --qf \"%{CHANGELOGTEXT}\n\" --specfile dist/beakerlib.spec 2> /dev/null | grep -v \"(none)\"'"

jobs:
  - job: copr_build
    trigger: pull_request
    targets:
      - fedora-all
      - centos-stream-8
      - centos-stream-9
      - centos-stream-10
      - epel-6
      - epel-all

  - job: copr_build
    trigger: commit
    branch: master
    targets:
      - fedora-all-x86_64
      - fedora-all-aarch64
      - centos-stream-8-x86_64
      - centos-stream-8-aarch64
      - centos-stream-8-s390x
      - centos-stream-8-ppc64le
      - centos-stream-9-x86_64
      - centos-stream-9-aarch64
      - centos-stream-9-s390x
      - centos-stream-9-ppc64le
      - centos-stream-10-x86_64
      - centos-stream-10-aarch64
      - centos-stream-10-s390x
      - centos-stream-10-ppc64le
      - epel-6-x86_64
      - epel-6-aarch64
      - epel-all-x86_64
      - epel-all-aarch64
      - epel-all-s390x
      - epel-all-ppc64le

  - job: tests
    trigger: pull_request
    targets:
      - fedora-latest-stable
      - epel-all

  - job: propose_downstream
    trigger: release
    dist_git_branches:
      - fedora-all
      - epel-all

  - job: koji_build
    trigger: commit
    allowed_pr_authors: ["packit", "sopos"]
    dist_git_branches:
      - fedora-all
      - epel-all

  - job: bodhi_update
    trigger: commit
    dist_git_branches:
      - fedora-branched
      - epel-all
