specfile_path: dist/beakerlib.spec
#synced_files:
#    - beakerlib.spec

upstream_package_name: beakerlib
downstream_package_name: beakerlib


#actions:
#  create-archive:
#  - make tarball
#  get-current-version:
#  - make version

jobs:
- job: copr_build
  trigger: pull_request
  metadata:
    targets:
    - fedora-all
    - centos-stream-8
    - centos-stream-9
    - epel-6
    - epel-all

- job: copr_build
  trigger: commit
  metadata:
    branch: master
    targets:
    - fedora-all
    - centos-stream-8
    - centos-stream-9
    - epel-6
    - epel-all
