specfile_path: dist/beakerlib.spec
#synced_files:
#    - beakerlib.spec

upstream_package_name: beakerlib
downstream_package_name: beakerlib

jobs:
- job: copr_build
  trigger: pull_request
  targets:
  - fedora-all
  - centos-stream-8
  - centos-stream-9
  - epel-6
  - epel-all

- job: copr_build
  trigger: commit
  branch: master
  targets:
  - fedora-all-x86_64
  - fedora-all-aarch64
  - centos-stream-8-x86_64
  - centos-stream-8-aarch64
  - centos-stream-9-x86_64
  - centos-stream-9-aarch64
  - epel-6-x86_64
  - epel-6-aarch64
  - epel-all-x86_64
  - epel-all-aarch64

- job: tests
  trigger: pull_request
  targets:
  - fedora-all
  - epel-8
